"""add gates gate_rank_profiles gate_shares

Revision ID: 0077d445e221
Revises: af99e45efd47
Create Date: 2026-03-04 07:01:36.645785

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0077d445e221'
down_revision: Union[str, None] = 'af99e45efd47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gate_rank_profiles',
    sa.Column('rank', sa.Enum('E', 'D', 'C', 'B', 'A', 'S', 'S_PLUS', name='gaterank'), nullable=False),
    sa.Column('stability_init', sa.Float(), nullable=False),
    sa.Column('volatility', sa.Float(), nullable=False),
    sa.Column('yield_min_micro', sa.BigInteger(), nullable=False),
    sa.Column('yield_max_micro', sa.BigInteger(), nullable=False),
    sa.Column('total_shares', sa.Integer(), nullable=False),
    sa.Column('lifespan_min', sa.Integer(), nullable=False),
    sa.Column('lifespan_max', sa.Integer(), nullable=False),
    sa.Column('collapse_threshold', sa.Float(), nullable=False),
    sa.Column('discovery_cost_micro', sa.BigInteger(), nullable=False),
    sa.Column('spawn_weight', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('rank')
    )
    op.create_table('gates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('rank', sa.Enum('E', 'D', 'C', 'B', 'A', 'S', 'S_PLUS', name='gaterank'), nullable=False),
    sa.Column('stability', sa.Float(), nullable=False),
    sa.Column('volatility', sa.Float(), nullable=False),
    sa.Column('base_yield_micro', sa.BigInteger(), nullable=False),
    sa.Column('total_shares', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('OFFERING', 'ACTIVE', 'UNSTABLE', 'COLLAPSED', name='gatestatus'), nullable=False),
    sa.Column('spawned_at_tick', sa.Integer(), nullable=False),
    sa.Column('collapsed_at_tick', sa.Integer(), nullable=True),
    sa.Column('discovery_type', sa.Enum('SYSTEM', 'PLAYER', name='discoverytype'), nullable=False),
    sa.Column('discoverer_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['discoverer_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['rank'], ['gate_rank_profiles.rank'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gate_shares',
    sa.Column('gate_id', sa.UUID(), nullable=False),
    sa.Column('player_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.CheckConstraint('quantity >= 0', name='ck_gate_shares_quantity_non_negative'),
    sa.ForeignKeyConstraint(['gate_id'], ['gates.id'], ),
    sa.PrimaryKeyConstraint('gate_id', 'player_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gate_shares')
    op.drop_table('gates')
    op.drop_table('gate_rank_profiles')
    # ### end Alembic commands ###