"""add admin role and simulation parameters

Revision ID: 2e9f2d2c75d9
Revises: 4df4626355da
Create Date: 2026-03-08 04:31:12.201410

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e9f2d2c75d9'
down_revision: Union[str, None] = '4df4626355da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('simulation_parameters',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.String(length=500), nullable=False),
    sa.Column('value_type', sa.Enum('INT', 'FLOAT', 'BOOL', 'STRING', name='paramvaluetype'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['updated_by'], ['players.id'], ),
    sa.PrimaryKeyConstraint('key')
    )
    # Enum must be created explicitly before add_column (autogenerate doesn't handle this)
    sa.Enum('PLAYER', 'ADMIN', name='playerrole').create(op.get_bind(), checkfirst=True)
    op.add_column('players', sa.Column('role', sa.Enum('PLAYER', 'ADMIN', name='playerrole', create_type=False), server_default='PLAYER', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'role')
    op.drop_table('simulation_parameters')
    sa.Enum(name='playerrole').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='paramvaluetype').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###