"""add leaderboard and seasons

Revision ID: 4df4626355da
Revises: 8921b1e0d286
Create Date: 2026-03-07 17:09:24.417662

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4df4626355da'
down_revision: Union[str, None] = '8921b1e0d286'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('seasons',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('season_number', sa.Integer(), nullable=False),
    sa.Column('start_tick', sa.Integer(), nullable=False),
    sa.Column('end_tick', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'COMPLETED', name='seasonstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('season_number')
    )
    op.create_table('player_net_worth',
    sa.Column('player_id', sa.UUID(), nullable=False),
    sa.Column('net_worth_micro', sa.BigInteger(), nullable=False),
    sa.Column('score_micro', sa.BigInteger(), nullable=False),
    sa.Column('balance_micro', sa.BigInteger(), nullable=False),
    sa.Column('portfolio_micro', sa.BigInteger(), nullable=False),
    sa.Column('last_active_tick', sa.Integer(), nullable=False),
    sa.Column('updated_at_tick', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('player_id')
    )
    op.create_table('season_results',
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.UUID(), nullable=False),
    sa.Column('final_rank', sa.Integer(), nullable=False),
    sa.Column('final_score_micro', sa.BigInteger(), nullable=False),
    sa.Column('final_net_worth_micro', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ),
    sa.PrimaryKeyConstraint('season_id', 'player_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('season_results')
    op.drop_table('player_net_worth')
    op.drop_table('seasons')
    # ### end Alembic commands ###