"""add orders trades market_prices and escrow entry types

Revision ID: 7030291f0b68
Revises: 0077d445e221
Create Date: 2026-03-04 12:26:55.344236

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7030291f0b68'
down_revision: Union[str, None] = '0077d445e221'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ── Add new enum values to existing entrytype ──
    # Must come before any table that references them.
    # ALTER TYPE ... ADD VALUE cannot run inside a transaction in older PG,
    # but Alembic runs each migration in its own transaction and PG 12+
    # supports ADD VALUE inside transactions.
    op.execute("ALTER TYPE entrytype ADD VALUE IF NOT EXISTS 'ESCROW_LOCK'")
    op.execute("ALTER TYPE entrytype ADD VALUE IF NOT EXISTS 'ESCROW_RELEASE'")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_prices',
    sa.Column('asset_type', sa.Enum('GATE_SHARE', 'GUILD_SHARE', name='assettype'), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('last_price_micro', sa.BigInteger(), nullable=True),
    sa.Column('best_bid_micro', sa.BigInteger(), nullable=True),
    sa.Column('best_ask_micro', sa.BigInteger(), nullable=True),
    sa.Column('volume_24h_micro', sa.BigInteger(), nullable=False),
    sa.Column('updated_at_tick', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('asset_type', 'asset_id')
    )
    op.create_table('orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('player_id', sa.UUID(), nullable=False),
    sa.Column('asset_type', sa.Enum('GATE_SHARE', 'GUILD_SHARE', name='assettype'), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('side', sa.Enum('BUY', 'SELL', name='orderside'), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price_limit_micro', sa.BigInteger(), nullable=False),
    sa.Column('filled_quantity', sa.Integer(), nullable=False),
    sa.Column('escrow_micro', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'PARTIAL', 'FILLED', 'CANCELLED', name='orderstatus'), nullable=False),
    sa.Column('created_at_tick', sa.Integer(), nullable=False),
    sa.Column('updated_at_tick', sa.Integer(), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.CheckConstraint('escrow_micro >= 0', name='ck_order_escrow_nonneg'),
    sa.CheckConstraint('filled_quantity >= 0', name='ck_order_filled_nonneg'),
    sa.CheckConstraint('price_limit_micro > 0', name='ck_order_price_positive'),
    sa.CheckConstraint('quantity > 0', name='ck_order_quantity_positive'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trades',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('buy_order_id', sa.UUID(), nullable=False),
    sa.Column('sell_order_id', sa.UUID(), nullable=False),
    sa.Column('asset_type', sa.Enum('GATE_SHARE', 'GUILD_SHARE', name='assettype'), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price_micro', sa.BigInteger(), nullable=False),
    sa.Column('buyer_fee_micro', sa.BigInteger(), nullable=False),
    sa.Column('seller_fee_micro', sa.BigInteger(), nullable=False),
    sa.Column('tick_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trades')
    op.drop_table('orders')
    op.drop_table('market_prices')
    # PostgreSQL does not support removing enum values.
    # ESCROW_LOCK and ESCROW_RELEASE will remain in the entrytype enum.
    # ### end Alembic commands ###