"""add players system_accounts ledger_entries

Revision ID: 9db8473f1dcd
Revises: 
Create Date: 2026-02-24 05:08:41.475181

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9db8473f1dcd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ledger_entries',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tick_id', sa.Integer(), nullable=True),
    sa.Column('debit_type', sa.Enum('PLAYER', 'SYSTEM', 'GUILD', name='accountentitytype'), nullable=False),
    sa.Column('debit_id', sa.UUID(), nullable=False),
    sa.Column('credit_type', sa.Enum('PLAYER', 'SYSTEM', 'GUILD', name='accountentitytype'), nullable=False),
    sa.Column('credit_id', sa.UUID(), nullable=False),
    sa.Column('amount_micro', sa.BigInteger(), nullable=False),
    sa.Column('entry_type', sa.Enum('STARTING_GRANT', 'YIELD_PAYMENT', 'TRADE_SETTLEMENT', 'TRADE_FEE', 'GATE_DISCOVERY', 'GUILD_CREATION', 'GUILD_MAINTENANCE', 'PORTFOLIO_MAINTENANCE', 'CONCENTRATION_PENALTY', 'LIQUIDITY_DECAY', 'DIVIDEND', 'AI_BUDGET', 'ADMIN_ADJUSTMENT', name='entrytype'), nullable=False),
    sa.Column('memo', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('amount_micro > 0', name='ck_ledger_amount_positive'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('players',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('balance_micro', sa.BigInteger(), nullable=False),
    sa.Column('is_ai', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('balance_micro >= 0', name='ck_players_balance_non_negative'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('system_accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_type', sa.Enum('TREASURY', name='accounttype'), nullable=False),
    sa.Column('balance_micro', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('balance_micro >= 0', name='ck_system_accounts_balance_non_negative'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_type')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('system_accounts')
    op.drop_table('players')
    op.drop_table('ledger_entries')
    # ### end Alembic commands ###