"""add guilds guild_members guild_shares guild_gate_holdings and order guild_id

Revision ID: f1da578fa5fc
Revises: 7030291f0b68
Create Date: 2026-03-05 04:44:22.367306

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1da578fa5fc'
down_revision: Union[str, None] = '7030291f0b68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guilds',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('founder_id', sa.UUID(), nullable=False),
    sa.Column('treasury_micro', sa.BigInteger(), nullable=False),
    sa.Column('total_shares', sa.Integer(), nullable=False),
    sa.Column('public_float_pct', sa.Numeric(), nullable=False),
    sa.Column('dividend_policy', sa.Enum('MANUAL', 'AUTO_FIXED_PCT', name='dividendpolicy'), nullable=False),
    sa.Column('auto_dividend_pct', sa.Numeric(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INSOLVENT', 'DISSOLVED', name='guildstatus'), nullable=False),
    sa.Column('created_at_tick', sa.Integer(), nullable=False),
    sa.Column('maintenance_cost_micro', sa.BigInteger(), nullable=False),
    sa.Column('missed_maintenance_ticks', sa.Integer(), nullable=False),
    sa.Column('insolvent_ticks', sa.Integer(), nullable=False),
    sa.CheckConstraint('treasury_micro >= 0', name='ck_guild_treasury_nonneg'),
    sa.ForeignKeyConstraint(['founder_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('guild_gate_holdings',
    sa.Column('guild_id', sa.UUID(), nullable=False),
    sa.Column('gate_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.CheckConstraint('quantity >= 0', name='ck_guild_gate_holding_nonneg'),
    sa.ForeignKeyConstraint(['gate_id'], ['gates.id'], ),
    sa.ForeignKeyConstraint(['guild_id'], ['guilds.id'], ),
    sa.PrimaryKeyConstraint('guild_id', 'gate_id')
    )
    op.create_table('guild_members',
    sa.Column('guild_id', sa.UUID(), nullable=False),
    sa.Column('player_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('LEADER', 'OFFICER', 'MEMBER', name='guildrole'), nullable=False),
    sa.Column('joined_at_tick', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['guild_id'], ['guilds.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('guild_id', 'player_id')
    )
    op.create_table('guild_shares',
    sa.Column('guild_id', sa.UUID(), nullable=False),
    sa.Column('player_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.CheckConstraint('quantity >= 0', name='ck_guild_share_quantity_nonneg'),
    sa.ForeignKeyConstraint(['guild_id'], ['guilds.id'], ),
    sa.PrimaryKeyConstraint('guild_id', 'player_id')
    )
    op.add_column('orders', sa.Column('guild_id', sa.UUID(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'guild_id')
    op.drop_table('guild_shares')
    op.drop_table('guild_members')
    op.drop_table('guild_gate_holdings')
    op.drop_table('guilds')
    # ### end Alembic commands ###